2020-08-14 21:23:07,885 [1] ?     - Application - Main is invoked

2020-08-14 21:23:13,302 [14] ?     - error! winter is coming!

2020-08-14 21:23:13,303 [14] ?     - critical! winter is coming!

2020-08-14 21:23:13,310 [14] ?     - Ошибочка вышла...

System.ApplicationException: Ошибочка вышла...
   at WebStore.Controllers.HomeController.Index() in C:\Users\kiruh\source\repos\WebStore_2020\UI\WebStore_2020\Controllers\HomeController.cs:line 36
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\Users\kiruh\source\repos\WebStore_2020\UI\WebStore_2020\Startup.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\Users\kiruh\source\repos\WebStore_2020\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\Users\kiruh\source\repos\WebStore_2020\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24
2020-08-14 21:23:13,394 [14] ?     - An unhandled exception has occurred while executing the request.

2020-08-14 21:23:47,780 [1] ?     - Application - Main is invoked

2020-08-14 21:23:48,433 [11] ?     - error! winter is coming!

2020-08-14 21:23:48,434 [11] ?     - critical! winter is coming!

